### ISSUE TITLE
Elite Dangerous  Horizon (French)

### ISSUE THREAD

**Issue by GettroLadalle** [Duke-Jones/ED-IBE#1]
Hello Duke-Jones,

As you already know:
I am bad in English,
 more bad in German,
 and my generation is (Elite first version), MSDOS Pascal therefore not very efficient with the current programing.

I play Elite Dangerous Horizon under Windows 8.1 all in FRENCH Version.

1) Import of log commander went well.
As against the Old-Regulated-Noise market data is not work (not catastrophic)

2) After several attempts I managed to market the import of market data, with EDMC returning as parameters:
-m% OUTPUTFILE% (and not as in the example for EDMC -m \%OUTPUTFILE\%)
Which automatically becomes:
-m \%OUTPUTFILE\%
So I think there is a small error [] IN ED-IBE - ED-IBE- ExtData - ExternalDataInterface.cs
Or is my English which I played bad.

3) The data import Market Journal and worked well for a Space Station, a Space Outpost and Spaceport on Earth

4) When viewing tables of the items are displayed in English.

Translation thus functions in the sense Import French => ED-IBE Table
But not in the sense Table ED-IBE => Visualization (station), there I sorry I have not yet found the relevant file.
Naturally for the translation problem I work with Fra setting

5°) It would be difficult to foresee a way to have fonts in the display tables for folks like me who have seen decreases.
"I know if you see no more stopped playing like a kid"  ; =)

Those are my comments, even sorry I can not do more

Again thank you for your work.

**Comment by GettroLadalle** [comment]
Naturally for the translation problem I work with Fra setting

**Comment by Duke-Jones** [comment]
HI , please do not collect so much data. 
I made some changes and you have to delete the database on more time
(in cause of this I did not officially release IBE now).

>  my generation is (Elite first version)

me too ;-)

> 1) Import of log commander went well.

ok

> As against the Old-Regulated-Noise market data is not work (not catastrophic)

Ok, I did some changes there...

> 2) After several attempts I managed to market the import of market data, with EDMC returning as parameters:
> -m% OUTPUTFILE% (and not as in the example for EDMC -m \%OUTPUTFILE\%)
> Which automatically becomes:
> -m \%OUTPUTFILE\%
> So I think there is a small error [] IN ED-IBE - ED-IBE- ExtData - ExternalDataInterface.cs
> Or is my English which I played bad.

yes, I fixed this. new marker is '!' instead of '%' which is a wildcard in sql

> 3) The data import Market Journal and worked well for a Space Station, a Space Outpost and Spaceport on Earth

ok

> 4) When viewing tables of the items are displayed in English.
> 
> Translation thus functions in the sense Import French => ED-IBE Table
> But not in the sense Table ED-IBE => Visualization (station), there I sorry I have not yet found the >relevant file.
> Naturally for the translation problem I work with Fra setting

For many of the new commodities are still existing no translations yet. 
And so the default names (english) are shown, even if another language is selected. 
The interface to update or edit the translations is one of the next steps.

> 5°) It would be difficult to foresee a way to have fonts in the display tables for folks like me who have >seen decreases.
> "I know if you see no more stopped playing like a kid" ; =)

maybe I can do something with the text size

> Those are my comments, even sorry I can not do more
> Again thank you for your work.

you're welcome, thank you

**Comment by Duke-Jones** [comment]
I released the initial version.
Please try again and make sure to delete the existing database !!!

**Comment by Duke-Jones** [comment]
hint: get the file ReadMe_deu.txt from the releases page and put it into a online translator.
There are some hints for beginning

**Comment by Duke-Jones** [comment]
completely fixed in v0.1.1 

https://github.com/Duke-Jones/ED-IBE/releases/v0.1.1
