### ISSUE TITLE
NVNC/VncServer dependency

### ISSUE THREAD

**Issue by DaCoolX** [Duke-Jones/ED-IBE#10]
The project depends on the VNC things but Visual Studio cannot resolve them, did I miss something in the setup dev-environment steps?

Sidenote: This link http://dev.mysql.com/tech-resources/articles/mysql-installer-for-windows.htmlvisual in the readme is 404.

**Comment by Duke-Jones** [comment]
should be fixed here : d427d2cda829da5465fcaeb2800d1c6b2c6fa8b5
