### ISSUE TITLE
Copy paste

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/ED-IBE#12]
When in the station too station , You cant copy the system station name , too use in maps
Would be good if any field , allows you to Crlt C Crtl V

**Comment by Duke-Jones** [comment]
YEEEEES, in the old RN I already integrated some copy menues.
In IBE I thought soooo often that I should re-intergrate this function quickly.
It will come again - definitely

**Comment by Duke-Jones** [comment]
implemented in v0.4.0
(https://github.com/Duke-Jones/ED-IBE/tree/v0.4.0)
