### ISSUE TITLE
Crashs while downloading latest EDDB dumpfiles

### ISSUE THREAD

**Issue by Flyffies** [Duke-Jones/ED-IBE#14]
The download started and killes the whole programm. No error message, nothing. 
Then the download would instantly crash. After deleting the files from my temp directory (btw would be nice to change the download directory) it downloaded the systems.json completely and then the same with the other files.

**Comment by Duke-Jones** [comment]
should be fixed in v0.4.0 
(https://github.com/Duke-Jones/ED-IBE/tree/v0.4.0)
