### ISSUE TITLE
crash after importing data from json

### ISSUE THREAD

**Issue by skwerlman** [Duke-Jones/ED-IBE#15]
after importing data from json, the app tries to reenable the ui, and crashes.

dump file: https://mega.nz/#!VI80xbzb!vXsWssmyrEhPLH3mEjN8n-s19_GYfCyIJxttIe5x-fc

log files: https://gist.github.com/skwerlman/813a07d1cea46add2ad2dffd8400e344

**Comment by Duke-Jones** [comment]
Should be fixed in the coming v0.4.0.
