### ISSUE TITLE
clr.dll crash/Windows 10

### ISSUE THREAD

**Issue by denali1** [Duke-Jones/ED-IBE#18]
ED-IBE 0.42 crashes on trying to import from EDDB.  .Net is latest versions available, Windows 10 Pro, 64-Bit
- System 
  - Provider 
  
  [ Name]  Windows Error Reporting 
  - EventID 1001 
  
  [ Qualifiers]  0 
  
  Level 4 
  
  Task 0 
  
  Keywords 0x80000000000000 
  - TimeCreated 
  
  [ SystemTime]  2016-10-18T23:10:20.181983600Z 
  
  EventRecordID 17002 
  
  Channel Application 
  
  Computer Zen 
  
  Security 
- EventData 
  
  120576420955 
  4 
  APPCRASH 
  Not available 
  0 
  ED-IBE.exe 
  0.4.2.0 
  58012666 
  clr.dll 
  4.6.1586.0 
  575a1507 
  c00000fd 
  000000000000d667 
  
  \?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER25AD.tmp.WERInternalMetadata.xml 
  C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ED-IBE.exe_4f9f32997418b9514c4fd15d69b4972761dbd7_a4851ddc_33523f11 
  
  0 
  0d8c1ca1-08d0-47fb-85ff-fbffd3d85b7a 
  0 
  edfc857838ab9e6ac15eb79a5e71f4bf 
- System 
  - Provider 
  
  [ Name]  Application Error 
  - EventID 1000 
  
  [ Qualifiers]  0 
  
  Level 2 
  
  Task 100 
  
  Keywords 0x80000000000000 
  - TimeCreated 
  
  [ SystemTime]  2016-10-18T23:10:12.644530900Z 
  
  EventRecordID 17001 
  
  Channel Application 
  
  Computer Zen 
  
  Security 
- EventData 
  
  ED-IBE.exe 
  0.4.2.0 
  58012666 
  clr.dll 
  4.6.1586.0 
  575a1507 
  c00000fd 
  000000000000d667 
  4be4 
  01d22994b0ded162 
  C:\Program Files\ED-IBE\ED-IBE.exe 
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll 
  0d8c1ca1-08d0-47fb-85ff-fbffd3d85b7a

**Comment by Duke-Jones** [comment]
Please send me the logs and the crash dumpfile. You can find them in the IBE data folder (depending on your installation) and the "Logs" subfolder
