### ISSUE TITLE
The application does not close completely

### ISSUE THREAD

**Issue by GettroLadalle** [Duke-Jones/ED-IBE#2]
Hello,
I just noticed one thing:
When we close the ED-IBE application, a part remains active, preventing restart the application.
One is forced to kill the application in Task Manager.
Have a nice week end

The problem appears to be random

**Comment by Duke-Jones** [comment]
fixed in 2a46519bfbce2762cde3fa3ef4f2387b21d62414

reason: sql process was not shut not down but IBE was waing for it
