### ISSUE TITLE
Wrong Price info

### ISSUE THREAD

**Issue by Sharkalone** [Duke-Jones/ED-IBE#21]
Got something weird here.

IBE says there's _clothing_ ("_vêtements_" in my french version) for me to buy in Tange Vision (Pangilagara syst.) but when i look in the market there's none. In the same time, "clothing" price is the same as _progenitor cells_ ("_cellules souches_" in my french version), 6746, which is imo a little too high...

IBE screen : http://hpics.li/4cea9b4

ED screen (frome Tange Vision market) : http://hpics.li/03464d6

**Comment by Duke-Jones** [comment]
has this bug happen again ?
Or is it possible a initialization problem ? 
(on the screenshot you have not done a route calculation)

**Comment by Sharkalone** [comment]
With or without calculation it's the same thing. I just check the "By Commodity" tab and all the clothing prices are really too high.

By example, on my actual location : 

IBE : ![2017-01-09](https://cloud.githubusercontent.com/assets/3669600/21781079/3f92fdf4-d6ae-11e6-8e8f-21f3f262e58a.png)

ED : ![screenshot_0005](https://cloud.githubusercontent.com/assets/3669600/21781120/64883af2-d6ae-11e6-8500-c0ee6cebc5bd.png)

**Comment by Duke-Jones** [comment]
oh, now I see .... this seems to be the price of "Electronique Grand Public".
I have to check this. Thanks for the moment.....

**Comment by Sharkalone** [comment]
Right!! Found it, it's not a bug, it's a bad translation.

i checked the csv and "Consumer Technology" is translated in "Vêtements" (Clothing) in my version. I don't know if it's an error on my side. The right translation in french is "Electronique Grand Public" indeed.

...and clothing ("Vêtements" in french) is translated in "Maquillage" ("Makeup" in english)......check the localization file will take more time than i thought......

**Comment by Duke-Jones** [comment]
Please check this and change your translation ("Data"->"Edit Localization", see also point 5 in the StarterTips file). I suggest to enable "english" and "french" and then order by commodity ID.
If you export the data to file and send it I can add the wrong and the missing french translations
in the next version. Thanks

PS: of course you also can edit the file and import it again. But for quick changes you can edit the
names directly in ED-IBE

**Comment by Sharkalone** [comment]
I was already on it. But i wasn't checking the translated ones.

**Comment by Duke-Jones** [comment]
>If you export the data to file and send it I can add the wrong and the missing french translations
>in the next version. Thanks

Can you send me your changes, please ? Would be fantastic :)

**Comment by Sharkalone** [comment]
I lost them with the last update. I had to start again & dont had many time to do it lately.

**Comment by Duke-Jones** [comment]
You lost them, really ? Should not happen. Sorry for this.

**Comment by Sharkalone** [comment]
My fault, i should have think of it. You add new translations in the update so they change the localization file and so overwrite local modifications. I forgot to export mine before the update so i lost them.

**Comment by Sharkalone** [comment]
Just sent you some changes from last night.

**Comment by Duke-Jones** [comment]
Thanks a lot, I added ths directly in the v0.6.3.
Before install make a backup of you translations, please (as precaution)

**Comment by Duke-Jones** [comment]
I close this issue, but more translations are welcome
