### ISSUE TITLE
Interverted columns?

### ISSUE THREAD

**Issue by Sharkalone** [Duke-Jones/ED-IBE#23]
Don't you think the "Demand" and "Supply" columns are interverted?

My point is, the "buy" column is for the price the player **buy it** so associated with the station **supply level** (and so the "Supply" column) and the "Sell" col is for the price player **sell it** so associated with the station **demand level** (and so the "Demand" col).

Here, you put the price players **buy** things next to the info of the **demand level** for stations and the price they **sell** things near the **supply level** info. Weird imo.

**Comment by Duke-Jones** [comment]
on the "By Station" tab ?

**Comment by Sharkalone** [comment]
Sorry, i forgot to say it. Yes in the "by Station" tab.

**Comment by Duke-Jones** [comment]
Yes it's weird. I will change this.
But you can change this also manual. 
Perform a right click on the left upper corner of the table.
There you can change values of the column "display index"

**Comment by Sharkalone** [comment]
I tried to do it with just draging the columns. Didn't think of this solution ^^'

Thanks

**Comment by Duke-Jones** [comment]
order is fixed in commit 870b916b6cd332f6ae21d4034de2f556d32f8f7b
