### ISSUE TITLE
wrong sorting in Prices/Profit

### ISSUE THREAD

**Issue by Sharkalone** [Duke-Jones/ED-IBE#27]
I think there is an issue with the sorting of some column. Here is a screen :

![2017-01-23](https://cloud.githubusercontent.com/assets/3669600/22219970/1db1704e-e1ad-11e6-920d-e984c5991c28.png)

My point is in the _Best trip_ calculation table on short trips(very short in this case ^^). when i like to sort the _Profit[Cr]_ column and you can see the sorting here is wrong between 3 and 4 digits profit. Confusion with string/number variables?

**Comment by Duke-Jones** [comment]
I'll have a look on it

**Comment by Duke-Jones** [comment]
fixed in 908c269d844dd1d3d37b74b9b58814d7db773376
