### ISSUE TITLE
ED-IBE sending incorrect data to EDDN

### ISSUE THREAD

**Issue by CRCError1970** [Duke-Jones/ED-IBE#28]
I believe that ED-IBE is sending data to the EDDN incorrectly.

For the past few days I've been having trouble with eddb.io showing that stations I've recently visited have only 1 supply of all commodities after I've let ED-IBE update the EDDN.

If I disable ED-IBE's market sharing data and use E:D Market Connector, everything updates correctly.

**Comment by Duke-Jones** [comment]
Please check, if your messages apear in the log: https://ross.eddb.io/eddn/log
Best is to set filter to "ED-IBE (API)" and then check the log.

Second thing to check: 
On ED-IBE both "Market Data" led's are lights up after you've been landed ?

**Comment by CRCError1970** [comment]
Ok, Just did that.

https://ross.eddb.io/eddn/log/9813833

It's sending Stock of 1 for everything. I'm at the station and the supply of explosives is 1,904,110 on screen.

Also, all LED's are lit indicating a successful update.

Just loaded Market Connector and this is the log:

https://ross.eddb.io/eddn/log/9814742

**Comment by Duke-Jones** [comment]
Uh, bad mistake. Thank you for beeing so attentive.
I will release a new version as soon as possible.

**Comment by Duke-Jones** [comment]
fixed in version v0.6.2 (ed941b964bd1d2fb996c6bf026382d8e9b677beb)

**Comment by CRCError1970** [comment]
Indeed! I imagine that all it takes is one little typo to completely render SQL stupid. :)
