### ISSUE TITLE
Commanders Log

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/ED-IBE#3]
Columns when clicked are sorted , by time date amount or grouped

Grouped; Notes if clicked groups all you notes at the top, recent to older

**Comment by wdburgdorf** [comment]
Crash on startup. Dump: https://goo.gl/D7xyGd

**Comment by Duke-Jones** [comment]
> Crash on startup. Dump: https://goo.gl/D7xyGd

Whatever it was, it should be fixed.

Please open a own issue next time.

cu in space, Duke

**Comment by Duke-Jones** [comment]
> Columns when clicked are sorted , by time date amount or grouped
> Grouped; Notes if clicked groups all you notes at the top, recent to older

it's much planned for the log, but I had not the time yet.

**Comment by Duke-Jones** [comment]
I will close this issue. The log is  not groupable nor sortable
but is has now a filter on the key columns.
If there's need for more be not afraid to contradict....
