### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by samscode** [Duke-Jones/ED-IBE#4]
ERROR: System.Exception: Error in main-init-routine ---> System.Exception: could't verify productpath and/or gamepath

It's looking for the wrong path... AppData\Local\Frontier_Developments\Products\elite-dangerous-64\AppConfig.xml (note the Frontier_Developments).

**Comment by Duke-Jones** [comment]
should be fixed here : 4cf2d8f7e8243bd1ce32b44acdf40423824300df

please be patient - new version will come soon
