### ISSUE TITLE
VNC

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/ED-IBE#5]
This first version ,(alpha-state) gave me a dump file , uploading to Github  on the tablet  it says 'The connection was reset'

https://www.dropbox.com/s/t2egyaf7p4qtdvj/VNC%20ed-ibe-dump-v0_3_1.zip?dl=0

**Comment by Duke-Jones** [comment]
Removed the VNC-option for the moment.
Not sure if I will continue development on this feature - there are too much problems

**Comment by sutex** [comment]
Yep ,VNC is very problematic ,
