### ISSUE TITLE
You have landed / Import market data

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/ED-IBE#6]
If those two button could be access via a Short cut key , then Voice attack ( keyboard) could be used to active them Thus when in game you don't have to Alt tab too desktop , every time you land too update market data 

This would allow IBE , too be used as is ( or until VNC is solution found) in that you could be docking collecting data ( in your local star system) , , then once offline sort your trades , but at least you have the data .. to start . Given ED latest update , Trading is having a  boom as player are finding AI bounty hunting is harder to make money,... :)

**Comment by Duke-Jones** [comment]
E:D 2.2 is coming with a new event log. 

With this it is possible to react directly due to game events like "landed" or "lift of".
I will link these events directly with the IBE functions like "collecting commodity data".
So you don't need to press any buttons for this in future.

**Comment by sutex** [comment]
cool

**Comment by Duke-Jones** [comment]
feature will come in v0.4.1 or v0.4.2 for E:D 2.2

**Comment by Duke-Jones** [comment]
automatic collecting of station data is included meanwhile
