### ISSUE TITLE
TabControlExt is referenced but doesn't exist.

### ISSUE THREAD

**Issue by DaCoolX** [Duke-Jones/ED-IBE#9]
Visual Studio complains about the following:
[Failure] Could not find file 'C:\ED-IBE\ED-IBE\Enums and Utility Classes\TabControlExt.Designer.cs'.
[Failure] Could not find file 'C:\ED-IBE\ED-IBE\Enums and Utility Classes\TabControlExt.cs'.

**Comment by Duke-Jones** [comment]
Oh - ok, but is should be possible without problems to remove the references. 

In the past I did some tests with the class and removed it then again.
Seems I forgot to remove the file from the project - sorry

**Comment by Duke-Jones** [comment]
should be fixed here : d427d2cda829da5465fcaeb2800d1c6b2c6fa8b5
